/* ================================================================
   THE CATALOG OF RITES — single source of truth for every exercise
   Powers: Combat Log picker, PRs, Grimoire plans, the Codex,
   the muscle heatmap, and the Fire Keeper's judgments.

   heat.primary / heat.secondary say which region of the Vessel's
   heatmap an exercise lights. Machine/cable/dumbbell variants share
   the same heat as the pattern they train — a "Machine Chest Press"
   lights the chest whatever brand of iron it is.
   ================================================================ */

export const MUSCLE_GROUPS = ['Shoulders', 'Chest', 'Back', 'Core', 'Legs', 'Arms'] as const
export type MuscleGroup = (typeof MUSCLE_GROUPS)[number]

export type Category = 'Chest' | 'Back' | 'Legs' | 'Shoulders' | 'Arms' | 'Core'

export type Exercise = {
  name: string
  category: Category
  compound: boolean
  primary: string[] // display muscles
  secondary: string[]
  heat: { primary: MuscleGroup[]; secondary: MuscleGroup[] } // avatar heatmap
  standard?: number // intermediate PR target, x bodyweight (Fire Keeper)
  cues: [string, string, string]
}

export const EXERCISES: Exercise[] = [
  /* ---------- chest ---------- */
  { name: 'Bench Press', category: 'Chest', compound: true, standard: 1.0,
    primary: ['Chest'], secondary: ['Front Delts', 'Triceps'],
    heat: { primary: ['Chest'], secondary: ['Shoulders', 'Arms'] },
    cues: ['Draw thy shoulder blades together, as a bow before the loose.', 'Lower the bar to the low chest — slow, silent, in control.', 'Drive thy feet into the earth; the whole body presses, not the arms alone.'] },
  { name: 'Incline Bench Press', category: 'Chest', compound: true,
    primary: ['Upper Chest'], secondary: ['Front Delts', 'Triceps'],
    heat: { primary: ['Chest'], secondary: ['Shoulders', 'Arms'] },
    cues: ['Set the bench as a rampart, thirty degrees toward heaven.', 'Bring the bar to the collar of thy armor, elbows tucked.', 'Press up and slightly back, toward the crown thou seekest.'] },
  { name: 'Dumbbell Bench Press', category: 'Chest', compound: true,
    primary: ['Chest'], secondary: ['Front Delts', 'Triceps'],
    heat: { primary: ['Chest'], secondary: ['Shoulders', 'Arms'] },
    cues: ['Two irons, twin oaths — each arm must hold its own.', 'Lower until a deep stretch pulls across the chest.', 'Press them together at the summit without clashing the bells.'] },
  { name: 'Machine Chest Press', category: 'Chest', compound: true,
    primary: ['Chest'], secondary: ['Triceps'],
    heat: { primary: ['Chest'], secondary: ['Arms'] },
    cues: ['Whatever the maker of the machine, the chest answers the same.', 'Set the seat so the handles meet thee at mid-chest.', 'Press smooth and full; let no clang of the stack rush thee.'] },
  { name: 'Cable Fly', category: 'Chest', compound: false,
    primary: ['Chest'], secondary: [],
    heat: { primary: ['Chest'], secondary: [] },
    cues: ['Soft elbows, as wings half-folded.', 'Draw the cables together as though embracing a great column.', 'Feel the stretch at the edges; the fibers sing where they part.'] },
  { name: 'Push-Up', category: 'Chest', compound: false,
    primary: ['Chest'], secondary: ['Core', 'Triceps'],
    heat: { primary: ['Chest'], secondary: ['Core', 'Arms'] },
    cues: ['Brace the core like iron; the body moves as a single slab of stone.', 'Descend until thy chest grazes the ground.', 'Drive the earth away from thee.'] },
  { name: 'Dip', category: 'Chest', compound: false,
    primary: ['Lower Chest'], secondary: ['Triceps', 'Front Delts'],
    heat: { primary: ['Chest'], secondary: ['Arms', 'Shoulders'] },
    cues: ['Lean forward as one peering into the abyss.', 'Descend until the shoulders sink just below the elbows — no further.', 'Press back to the summit without swinging; the iron respects stillness.'] },

  /* ---------- back ---------- */
  { name: 'Deadlift', category: 'Back', compound: true, standard: 1.75,
    primary: ['Posterior Chain'], secondary: ['Lats', 'Core', 'Grip'],
    heat: { primary: ['Back'], secondary: ['Legs', 'Core', 'Arms'] },
    cues: ['Wedge thyself against the bar; take the slack as a held breath.', 'The bar climbs thy legs like ivy up a keep.', 'Stand tall at the summit. Do not lean back into ruin.'] },
  { name: 'Barbell Row', category: 'Back', compound: true, standard: 0.9,
    primary: ['Lats', 'Mid Back'], secondary: ['Biceps', 'Core'],
    heat: { primary: ['Back'], secondary: ['Arms', 'Shoulders', 'Core'] },
    cues: ['Hinge and hold — the torso is a drawbridge, lowered and locked.', 'Tear the bar to thy waist as a blade from the earth.', 'Let no heave of the hips steal what the back must earn.'] },
  { name: 'Seated Cable Row', category: 'Back', compound: true,
    primary: ['Mid Back', 'Lats'], secondary: ['Biceps'],
    heat: { primary: ['Back'], secondary: ['Arms'] },
    cues: ['Sit tall; the chest is a shield, not a slouch.', 'Pull the handle to thy navel, driving the elbows past thy ribs.', 'Let the weight draw thee forward only so far as the shoulder blades allow.'] },
  { name: 'T-Bar Row', category: 'Back', compound: true,
    primary: ['Mid Back', 'Lats'], secondary: ['Biceps'],
    heat: { primary: ['Back'], secondary: ['Arms'] },
    cues: ['Hinge over the landmine as over an anvil.', 'Row the weight to thy chest, squeezing the blades at the top.', 'Lower under command — the eccentric is half the rite.'] },
  { name: 'Machine Row', category: 'Back', compound: true,
    primary: ['Lats', 'Mid Back'], secondary: ['Biceps'],
    heat: { primary: ['Back'], secondary: ['Arms'] },
    cues: ['Any brand of row-machine will forge the same broad back.', 'Set the pad against thy chest and pull the handles home.', 'Pause a breath at the squeeze before the stack descends.'] },
  { name: 'Pull-Up', category: 'Back', compound: false,
    primary: ['Lats'], secondary: ['Biceps', 'Rear Delts'],
    heat: { primary: ['Back'], secondary: ['Arms', 'Shoulders'] },
    cues: ['Hang as the condemned; rise as the chosen.', 'Pull thine elbows to thy ribs, not thy chin to the bar.', 'Descend with control — the fall teaches as much as the rise.'] },
  { name: 'Lat Pulldown', category: 'Back', compound: false,
    primary: ['Lats'], secondary: ['Biceps'],
    heat: { primary: ['Back'], secondary: ['Arms'] },
    cues: ['Sit tall; anchor thy thighs beneath the pads as roots beneath stone.', 'Draw the bar to thy collarbone, chest rising to meet it.', 'Resist the return — the cable is a serpent that must not escape.'] },
  { name: 'Rack Pull', category: 'Back', compound: true,
    primary: ['Posterior Chain', 'Traps'], secondary: ['Grip'],
    heat: { primary: ['Back'], secondary: ['Legs', 'Arms'] },
    cues: ['Set the pins at thy knees; the road is short but heavy.', 'Brace, then drag the bar up thy thighs to a proud lockout.', 'Guard thy spine — pride here is paid for in the morning.'] },

  /* ---------- legs ---------- */
  { name: 'Squat', category: 'Legs', compound: true, standard: 1.5,
    primary: ['Quads', 'Glutes'], secondary: ['Core'],
    heat: { primary: ['Legs'], secondary: ['Core'] },
    cues: ['Root thy feet; grip the ground as talons grip prey.', 'Sit between thy legs — three breaths down, chest proud.', 'Rise as though the sky itself resists thee.'] },
  { name: 'Front Squat', category: 'Legs', compound: true,
    primary: ['Quads'], secondary: ['Core', 'Upper Back'],
    heat: { primary: ['Legs'], secondary: ['Core', 'Back'] },
    cues: ['Rack the bar upon thy collar as a yoke of office; elbows to the sky.', 'Stay upright — to bow forward is to drop the crown.', 'Descend deep, and rise leading with the elbows.'] },
  { name: 'Bulgarian Split Squat', category: 'Legs', compound: false,
    primary: ['Quads', 'Glutes'], secondary: ['Core'],
    heat: { primary: ['Legs'], secondary: ['Core'] },
    cues: ['One foot enthroned behind thee; the front leg bears the covenant alone.', 'Descend straight as a plumb line, knee tracking o’er the toes.', 'Endure. This one is meant to hurt.'] },
  { name: 'Goblet Squat', category: 'Legs', compound: false,
    primary: ['Quads', 'Glutes'], secondary: ['Core'],
    heat: { primary: ['Legs'], secondary: ['Core'] },
    cues: ['Cradle the iron at thy chest as a chalice of ember.', 'Sit straight down between thy heels, elbows brushing the knees.', 'Rise tall; let the chalice never spill.'] },
  { name: 'Romanian Deadlift', category: 'Legs', compound: false,
    primary: ['Hamstrings', 'Glutes'], secondary: ['Lower Back'],
    heat: { primary: ['Legs'], secondary: ['Back'] },
    cues: ['Push thy hips back as if closing a great door behind thee.', 'The bar never strays from thy legs — keep the blade sheathed close.', 'Descend only while the hamstrings sing; rise before they scream.'] },
  { name: 'Leg Press', category: 'Legs', compound: false,
    primary: ['Quads', 'Glutes'], secondary: ['Hamstrings'],
    heat: { primary: ['Legs'], secondary: [] },
    cues: ['Set thy feet upon the sled as upon a castle gate to be forced.', 'Lower until the knees near thy chest, spine pinned to the seat.', 'Never let the knees lock in arrogance at the top.'] },
  { name: 'Hack Squat', category: 'Legs', compound: false,
    primary: ['Quads'], secondary: ['Glutes'],
    heat: { primary: ['Legs'], secondary: [] },
    cues: ['Set thy back against the sled as against a portcullis.', 'Descend deep, knees tracking over the toes.', 'Drive through the whole foot; the quads carry this vigil.'] },
  { name: 'Leg Extension', category: 'Legs', compound: false,
    primary: ['Quads'], secondary: [],
    heat: { primary: ['Legs'], secondary: [] },
    cues: ['Pin thy hips to the seat; only the knees may speak.', 'Straighten the legs and pause at the summit, quads locked.', 'Lower slow — the burn is the whole sermon.'] },
  { name: 'Leg Curl', category: 'Legs', compound: false,
    primary: ['Hamstrings'], secondary: ['Calves'],
    heat: { primary: ['Legs'], secondary: [] },
    cues: ['Lay flat, hips down; let no arch cheat the pull.', 'Curl thy heels to thy seat with intent.', 'Fight the return through a slow, honest count.'] },
  { name: 'Hip Thrust', category: 'Legs', compound: false,
    primary: ['Glutes'], secondary: ['Hamstrings', 'Core'],
    heat: { primary: ['Legs'], secondary: ['Core'] },
    cues: ['Shoulders upon the bench, crown of a fallen throne.', 'Drive through the heels until thy hips lock at the summit.', 'Hold one breath at the top — tribute must be paid in full.'] },
  { name: 'Walking Lunge', category: 'Legs', compound: false,
    primary: ['Quads', 'Glutes'], secondary: ['Core'],
    heat: { primary: ['Legs'], secondary: ['Core'] },
    cues: ['March as a pilgrim under a full pack.', 'Sink the back knee near the ground, torso tall.', 'Drive through the front heel to rise into the next step.'] },
  { name: 'Calf Raise', category: 'Legs', compound: false,
    primary: ['Calves'], secondary: [],
    heat: { primary: ['Legs'], secondary: [] },
    cues: ['Rise upon the balls of thy feet as one reaching a high shelf.', 'Pause at the peak; the calves are stubborn and must be held to account.', 'Descend into a deep stretch before the next ascent.'] },

  /* ---------- shoulders ---------- */
  { name: 'Overhead Press', category: 'Shoulders', compound: true, standard: 0.66,
    primary: ['Delts'], secondary: ['Triceps', 'Core'],
    heat: { primary: ['Shoulders'], secondary: ['Core', 'Arms'] },
    cues: ['Brace thy trunk as a keep withstands siege.', 'Squeeze the bar to wake the arms, and press without leaning.', 'Once past thy crown, drive the skull through the window.'] },
  { name: 'Arnold Press', category: 'Shoulders', compound: true,
    primary: ['Delts'], secondary: ['Triceps'],
    heat: { primary: ['Shoulders'], secondary: ['Arms'] },
    cues: ['Begin with palms toward thee, as if guarding thy face.', 'Rotate and press in one flowing rite until the palms face out.', 'Reverse the turn on the descent — slow, deliberate.'] },
  { name: 'Machine Shoulder Press', category: 'Shoulders', compound: true,
    primary: ['Delts'], secondary: ['Triceps'],
    heat: { primary: ['Shoulders'], secondary: ['Arms'] },
    cues: ['Any maker of the press-machine will raise the same delts.', 'Set the seat so the handles rest at thy shoulders.', 'Press to a soft lockout; spare the elbows the final slam.'] },
  { name: 'Lateral Raise', category: 'Shoulders', compound: false,
    primary: ['Side Delts'], secondary: [],
    heat: { primary: ['Shoulders'], secondary: [] },
    cues: ['Raise the iron as wings unfurling, elbows soft.', 'Halt at the horizon — no higher.', 'Lower slower than thou rose. The descent is the sermon.'] },
  { name: 'Rear Delt Fly', category: 'Shoulders', compound: false,
    primary: ['Rear Delts'], secondary: ['Upper Back'],
    heat: { primary: ['Shoulders'], secondary: ['Back'] },
    cues: ['Hinge forward, or lie upon the incline as upon a bier.', 'Sweep the irons wide, leading with the elbows.', 'Squeeze the blades a breath before lowering.'] },
  { name: 'Face Pull', category: 'Shoulders', compound: false,
    primary: ['Rear Delts'], secondary: ['Upper Back'],
    heat: { primary: ['Shoulders'], secondary: ['Back'] },
    cues: ['Draw the rope to thy brow, elbows high as raised shields.', 'Pull the hands apart at the end, as if tearing a scroll.', 'Light iron, high count — this is a rite of maintenance, not glory.'] },

  /* ---------- arms ---------- */
  { name: 'Barbell Curl', category: 'Arms', compound: false,
    primary: ['Biceps'], secondary: ['Forearms'],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Pin thine elbows to thy flanks; they are anchors, not hinges of the swing.', 'Curl the iron in a proud arc, wrists unbending.', 'Lower through three slow counts. Cheated reps feed no fire.'] },
  { name: 'Dumbbell Curl', category: 'Arms', compound: false,
    primary: ['Biceps'], secondary: ['Forearms'],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Two irons, curled in turn or as one.', 'Turn the pinky toward thy shoulder at the top for the full squeeze.', 'Resist the descent; gravity is a thief.'] },
  { name: 'Hammer Curl', category: 'Arms', compound: false,
    primary: ['Biceps', 'Forearms'], secondary: [],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Hold the irons as hammers, thumbs to the sky.', 'Curl without turning the wrist; the forearm shares this toil.', 'Keep the elbows still and the tempo honest.'] },
  { name: 'Preacher Curl', category: 'Arms', compound: false,
    primary: ['Biceps'], secondary: ['Forearms'],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Lay thine arms upon the lectern; there is no hiding here.', 'Curl to the top, then lower until the arms near full length.', 'No swing, no momentum — the preacher brooks no lies.'] },
  { name: 'Tricep Pushdown', category: 'Arms', compound: false,
    primary: ['Triceps'], secondary: [],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Pin the elbows to thy sides as pegs to a wall.', 'Drive the handle down until the arms lock, then squeeze.', 'Let it rise only to the elbows’ bend — no higher.'] },
  { name: 'Skull Crusher', category: 'Arms', compound: false,
    primary: ['Triceps'], secondary: [],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Lower the iron toward thy brow with reverence, not haste.', 'Keep the elbows narrow and pointed to the sky.', 'Extend to lockout; the name is a warning, not a dare.'] },
  { name: 'Overhead Tricep Extension', category: 'Arms', compound: false,
    primary: ['Triceps'], secondary: [],
    heat: { primary: ['Arms'], secondary: [] },
    cues: ['Raise the iron overhead as a torch against the dark.', 'Lower behind thy skull for a deep stretch of the long head.', 'Extend fully; keep the elbows from flaring like broken gates.'] },
  { name: 'Close-Grip Bench Press', category: 'Arms', compound: true,
    primary: ['Triceps'], secondary: ['Chest', 'Front Delts'],
    heat: { primary: ['Arms'], secondary: ['Chest', 'Shoulders'] },
    cues: ['Grip within shoulder-width; the triceps take the crown here.', 'Tuck the elbows close and lower to the low chest.', 'Press straight up; let the arms, not the shoulders, drive.'] },

  /* ---------- core ---------- */
  { name: 'Plank', category: 'Core', compound: false,
    primary: ['Core'], secondary: ['Shoulders', 'Glutes'],
    heat: { primary: ['Core'], secondary: ['Shoulders', 'Legs'] },
    cues: ['Become the drawbridge — rigid from crown to heel.', 'Squeeze the glutes and brace as if awaiting a blow.', 'Breathe shallow and steady; the trembling is the offering.'] },
  { name: 'Hanging Leg Raise', category: 'Core', compound: false,
    primary: ['Core'], secondary: ['Grip'],
    heat: { primary: ['Core'], secondary: ['Arms'] },
    cues: ['Hang still; kill the swing before thou dost begin.', 'Raise the legs with the belly, not the hips’ momentum.', 'Lower under command — the descent writes the lesson.'] },
  { name: 'Cable Crunch', category: 'Core', compound: false,
    primary: ['Core'], secondary: [],
    heat: { primary: ['Core'], secondary: [] },
    cues: ['Kneel before the tower, rope framing thy skull.', 'Crunch with the abs, curling the ribs toward the hips.', 'Let the hips stay fixed; only the spine may bow.'] },
  { name: 'Russian Twist', category: 'Core', compound: false,
    primary: ['Core', 'Obliques'], secondary: [],
    heat: { primary: ['Core'], secondary: [] },
    cues: ['Sit as on a throne tilted back, feet light.', 'Rotate the iron from flank to flank with control.', 'Turn from the waist, not the arms; the obliques stand trial.'] },
  { name: "Farmer's Carry", category: 'Core', compound: false,
    primary: ['Core', 'Grip'], secondary: ['Traps', 'Upper Back'],
    heat: { primary: ['Core', 'Arms'], secondary: ['Back'] },
    cues: ['Take up the burdens as a pilgrim takes up penance.', 'Walk tall — shoulders back, ribs stacked over hips.', 'Set the iron down with dignity, not surrender.'] },
]

const BY_NAME = new Map(EXERCISES.map((e) => [e.name, e]))

export const getExercise = (name: string) => BY_NAME.get(name)

export const CATEGORIES: Category[] = ['Chest', 'Back', 'Legs', 'Shoulders', 'Arms', 'Core']
